const NS = '@tripify/App';

export const SPOTIFY_CODE_REQUEST = `${NS}/SPOTIFY_CODE_REQUEST`;
export const SPOTIFY_CODE_SUCCESS = `${NS}/SPOTIFY_CODE_SUCCESS`;
export const SPOTIFY_CODE_FAILURE = `${NS}/SPOTIFY_CODE_FAILURE`

export const SPOTIFY_TOKEN_REQUEST = `${NS}/SPOTIFY_TOKEN_REQUEST`;
export const SPOTIFY_TOKEN_SUCCESS = `${NS}/SPOTIFY_TOKEN_SUCCESS`;
export const SPOTIFY_TOKEN_FAILURE = `${NS}/SPOTIFY_TOKEN_FAILURE`;

export const GET_USER_PROFILE_REQUEST = `${NS}/GET_USER_PROFILE_REQUEST`;
export const GET_USER_PROFILE_SUCCESS = `${NS}/GET_USER_PROFILE_SUCCESS`;
export const GET_USER_PROFILE_FAILURE = `${NS}/GET_USER_PROFILE_FAILURE`;

export const LOGOUT_REQUEST = `${NS}/LOGOUT_REQUEST`;
export const LOGOUT_SUCCESS = `${NS}/LOGOUT_SUCCESS`;

export const CREATE_PLAYLIST_REQUEST = `${NS}/CREATE_PLAYLIST_REQUEST`;
export const CREATE_PLAYLIST_SUCCESS = `${NS}/CREATE_PLAYLIST_SUCCESS`;
export const CREATE_PLAYLIST_FAILURE = `${NS}/CREATE_PLAYLIST_FAILURE`;

export const GET_TOP_ARTISTS_REQUEST = `${NS}/GET_TOP_ARTISTS_REQUEST`;
export const GET_TOP_ARTISTS_SUCCESS = `${NS}/GET_TOP_ARTISTS_SUCCESS`;
export const GET_TOP_ARTISTS_FAILURE = `${NS}/GET_TOP_ARTISTS_FAILURE`;